#!/bin/bash

cd src
javac dev/mitchellturton/chess/display/ChessGraphics.java -d ../bin/dev/mitchellturton/chess/display/
javac dev/mitchellturton/chess/App.java -d ../bin/dev/mitchellturton/chess/

cd ../bin
java dev/mitchellturton/chess/App